export const Monster = [
  {
    id: 1,
    nombre: "Godzilla",
    tipo: "Kaiju",
    altura: "50 metros",
    color: "Verde",
    texturaPiel: "Escamosa",
  },
  {
    id: 2,
    nombre: "Drácula",
    tipo: "Vampiro",
    altura: "1.80 metros",
    color: "Blanco pálido",
    texturaPiel: "Suave",
  },
  {
    id: 3,
    nombre: "El Hombre Lobo",
    tipo: "Licántropo",
    altura: "2.10 metros",
    color: "Marrón",
    texturaPiel: "Peluda",
  },
  {
    id: 4,
    nombre: "Frankenstein",
    tipo: "Monstruo",
    altura: "2.50 metros",
    color: "Verde pálido",
    texturaPiel: "Cicatrizada",
  },
  {
    id: 5,
    nombre: "King Kong",
    tipo: "Kaiju",
    altura: "30 metros",
    color: "Marrón oscuro",
    texturaPiel: "Peluda",
  },
];
